version : 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.10.6
    steps:
      - checkout
      - run: 
          name: Checking Python version
          command: python --version
      - run:
          name: Installing Flask
          command: pip install flask

workflows:
  python-workflow:
    jobs:
      - build
      